runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: 20.18.0
        registry-url: https://registry.npmjs.org
        cache: yarn

    - name: Disable Yarn scripts on CI
      run: yarn config set enableScripts false
      shell: bash

    - run: yarn install --immutable
      shell: bash
